# Generated by Django 5.0.3 on 2024-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fechaFundacion', models.DateField()),
                ('tipoDeGobierno', models.CharField(max_length=100)),
                ('poblacion', models.BigIntegerField()),
                ('continente', models.CharField(choices=[('África', 'AFRICA'), ('América', 'AMERICA'), ('Asia', 'ASIA'), ('Europa', 'EUROPA'), ('Oceanía', 'OCEANIA')], max_length=20)),
                ('PIB', models.BigIntegerField()),
                ('moneda', models.CharField(max_length=30)),
            ],
        ),
    ]
